name: Publish Python ğŸ distributions ğŸ“¦ to PyPI and TestPyPI

on: push

jobs:
  build-n-publish:
    name: Build and publish Python ğŸ distributions ğŸ“¦ to PyPI and TestPyPI

    strategy:
      matrix:
        python-version: ["3.9"]
        os: ["macOS-latest", "windows-latest", "ubuntu-latest"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master
    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        # nvironment variables donâ€™t persist between steps in a workflow, which breaks some things in Conda. 
        # Installing the environmentâ€™s packages into the base environment avoids this issue
        activate-environment: base
        python-version: ${{ matrix.python-version }}
        auto-activate-base: true
        channel-priority: true
        environment-file: env.yml
    
    - name: Install pypa/build
      shell: bash -l {0}
      run: |
        conda install wheel pytest
        make test
        make wheel
    
    - name: Store the ${{ matrix.os }} wheel
        uses: actions/upload-artifact@v2
        with:
          name: python-package-distributions
          path: dist

  deploy:
      name: Publish ğŸğŸ“¦ to (Test)PyPI
      runs-on: ubuntu-latest

      steps:
        - name: Download all the dists
          uses: actions/download-artifact@v2
          with:
            name: python-package-distributions
            path: dist

      - name: Publish distribution ğŸ“¦ to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          packages_dir: dist
          verbose: true
          skip_existing: true
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish distribution ğŸ“¦ to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          packages_dir: dist
          verbose: true
          skip_existing: true
          password: ${{ secrets.PYPI_API_TOKEN }}