name: test conda setup

on: push

jobs:
  build-n-publish:
    name: test conda setup

    strategy:
      matrix:
        python-version: ["3.9"]
        os: [macOS-latest, windows-latest, ubuntu-18.04]

    runs-on: ${{ matrix.os }}
    # timeout-minutes: 480
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@master
    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        miniconda-version: "latest"
        # environment variables don‚Äôt persist between steps in a workflow, which breaks some things in Conda.
        # Installing the environment‚Äôs packages into the base environment avoids this issue
        activate-environment: ""
        python-version: ${{ matrix.python-version }}
        auto-activate-base: true
        channel-priority: true
        environment-file: env.yml
        miniforge-variable: Mambaforge
        use-mamba: true

    - name: Install pypa/build
      shell: bash -l {0}
      run: |
        conda install wheel pytest
        make test
        make wheel

    - name: Store the ${{ matrix.os }} wheel
      uses: actions/upload-artifact@v2
      with:
        name: python-package-distributions
        path: src/dist/

  # deploy:
  #   name: Publish üêçüì¶ to (Test)PyPI
  #   needs:
  #     - build-n-publish
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Download all the dists
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: python-package-distributions
  #         path: dist/

  #     - name: Publish distribution üì¶ to Test PyPI
  #       uses: pypa/gh-action-pypi-publish@master
  #       with:
  #         packages_dir: dist/
  #         verbose: true
  #         skip_existing: true
  #         password: ${{ secrets.TEST_PYPI_API_TOKEN }}
  #         repository_url: https://test.pypi.org/legacy/

  #     - name: Publish distribution üì¶ to PyPI
  #       if: startsWith(github.ref, 'refs/tags')
  #       uses: pypa/gh-action-pypi-publish@master
  #       with:
  #         packages_dir: dist/
  #         verbose: true
  #         skip_existing: true
  #         password: ${{ secrets.PYPI_API_TOKEN }}